version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - "my_network"
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - "my_network"
    depends_on:
      - backend
    restart: always
networks:
   my_network:
